"""add order specifications

Revision ID: 1311ca84b6dd
Revises: 3395c032beb2
Create Date: 2026-06-22 13:54:19.058163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1311ca84b6dd'
down_revision: Union[str, Sequence[str], None] = '3395c032beb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('orders', sa.Column('order_specifications', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_specifications')
    # ### end Alembic commands ###
