"""add media fields

Revision ID: 4ff3ac127cc4
Revises: f66f0de5ad8f
Create Date: 2026-03-19 13:49:33.718078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ff3ac127cc4'
down_revision: Union[str, Sequence[str], None] = 'f66f0de5ad8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.add_column('delivery_partners', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('delivery_partners', sa.Column('vehicle_image_url', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.add_column('listings', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'logo_url')
    op.drop_column('listings', 'video_url')
    op.drop_column('listings', 'image_urls')
    op.drop_column('delivery_partners', 'vehicle_image_url')
    op.drop_column('delivery_partners', 'profile_image_url')
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preferred_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('bookings_customer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('bookings_listing_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('bookings_seller_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###
