"""add delivery pricing fields to orders

Revision ID: 6326dec8c92d
Revises: 24f2d309a3f3
Create Date: 2026-05-02 12:34:02.243519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6326dec8c92d'
down_revision: Union[str, Sequence[str], None] = '24f2d309a3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_city_requests_id'), 'city_requests', ['id'], unique=False)
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    
    op.add_column('merchants', sa.Column('pickup_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_merchants_city_id'), 'merchants', ['city_id'], unique=False)
    op.drop_constraint(op.f('merchants_city_id_fkey'), 'merchants', type_='foreignkey')
    op.create_foreign_key(None, 'merchants', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('delivery_price', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_days', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('distance_km', sa.Float(), nullable=True))
    op.create_index(op.f('ix_users_city_id'), 'users', ['city_id'], unique=False)
    op.drop_constraint(op.f('users_city_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_city_id_fkey'), 'users', 'cities', ['city_id'], ['id'])
    op.drop_index(op.f('ix_users_city_id'), table_name='users')
    op.drop_column('orders', 'distance_km')
    op.drop_column('orders', 'estimated_delivery_days')
    op.drop_column('orders', 'delivery_price')
    op.drop_constraint(None, 'merchants', type_='foreignkey')
    op.create_foreign_key(op.f('merchants_city_id_fkey'), 'merchants', 'cities', ['city_id'], ['id'])
    op.drop_index(op.f('ix_merchants_city_id'), table_name='merchants')
    op.drop_column('merchants', 'pickup_address')
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_index(op.f('ix_city_requests_id'), table_name='city_requests')
    op.drop_table('city_requests')
    # ### end Alembic commands ###
