"""add delivery route system

Revision ID: 75371a79f08d
Revises: 755ba6da9a68
Create Date: 2026-04-28 18:34:58.840978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75371a79f08d'
down_revision: Union[str, Sequence[str], None] = '755ba6da9a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('route_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_city_id', sa.Integer(), nullable=True),
    sa.Column('destination_city_id', sa.Integer(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['origin_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_requests_id'), 'route_requests', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_city_id', sa.Integer(), nullable=False),
    sa.Column('destination_city_id', sa.Integer(), nullable=False),
    sa.Column('estimated_days_min', sa.Integer(), nullable=False),
    sa.Column('estimated_days_max', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destination_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['origin_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_city_id', 'destination_city_id', name='unique_route')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('route_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.String(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_pricing_id'), 'route_pricing', ['id'], unique=False)
   


def downgrade() -> None:
    op.drop_index(op.f('ix_route_pricing_id'), table_name='route_pricing')
    op.drop_table('route_pricing')

    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')

    op.drop_index(op.f('ix_route_requests_id'), table_name='route_requests')
    op.drop_table('route_requests')

    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
