"""recreate delivery partners with user link

Revision ID: 7f47f540d87a
Revises: d1eab84964cd
Create Date: 2026-03-01 08:28:43.165369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f47f540d87a'
down_revision: Union[str, Sequence[str], None] = 'd1eab84964cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('operating_city', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('completed_deliveries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_delivery_partners_id'), 'delivery_partners', ['id'], unique=False)
    op.create_foreign_key(None, 'delivery_matches', 'delivery_partners', ['delivery_partner_id'], ['id'])
    op.alter_column('delivery_requests', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('delivery_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_requests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_requests', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'delivery_matches', type_='foreignkey')
    op.drop_index(op.f('ix_delivery_partners_id'), table_name='delivery_partners')
    op.drop_table('delivery_partners')
    # ### end Alembic commands ###
