"""delivery lifecycle integration

Revision ID: b5d39e673914
Revises: fc2c83eb4e3f
Create Date: 2026-02-27 23:28:25.770080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5d39e673914'
down_revision: Union[str, Sequence[str], None] = 'fc2c83eb4e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_requests', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('delivery_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'assigned', 'completed', name='deliveryrequeststatus'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('delivery_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('delivery_requests_assigned_partner_id_fkey'), 'delivery_requests', type_='foreignkey')
    op.drop_constraint(op.f('delivery_requests_seller_id_fkey'), 'delivery_requests', type_='foreignkey')
    op.drop_constraint(op.f('delivery_requests_order_id_fkey'), 'delivery_requests', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_requests', 'merchants', ['seller_id'], ['id'])
    op.create_foreign_key(None, 'delivery_requests', 'orders', ['order_id'], ['id'])
    op.drop_column('delivery_requests', 'assigned_partner_id')
    op.drop_constraint(op.f('orders_delivery_request_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_delivery_request_id_fkey'), 'orders', 'delivery_requests', ['delivery_request_id'], ['id'])
    op.add_column('delivery_requests', sa.Column('assigned_partner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'delivery_requests', type_='foreignkey')
    op.drop_constraint(None, 'delivery_requests', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_requests_order_id_fkey'), 'delivery_requests', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('delivery_requests_seller_id_fkey'), 'delivery_requests', 'merchants', ['seller_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('delivery_requests_assigned_partner_id_fkey'), 'delivery_requests', 'delivery_partners', ['assigned_partner_id'], ['id'])
    op.alter_column('delivery_requests', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_requests', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'assigned', 'completed', name='deliveryrequeststatus'),
               nullable=False)
    op.alter_column('delivery_requests', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
