"""Add delivery fields to order

Revision ID: ba5174938481
Revises: 0bb5d0145c96
Create Date: 2026-02-25 23:00:14.893006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5174938481'
down_revision: Union[str, Sequence[str], None] = '0bb5d0145c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'delivery_requests', ['delivery_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_request_id')
    op.drop_column('orders', 'delivery_method')
    # ### end Alembic commands ###
