"""add city_id to merchant and user

Revision ID: c3cd7cbf75f1
Revises: 75371a79f08d
Create Date: 2026-04-29 17:28:43.723749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3cd7cbf75f1'
down_revision: Union[str, Sequence[str], None] = '75371a79f08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_constraint(op.f('delivery_requests_order_id_fkey'), 'delivery_requests', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_requests', 'orders', ['order_id'], ['id'])
    op.add_column('merchants', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'merchants', 'cities', ['city_id'], ['id'])
    op.add_column('users', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'city_id')
    op.drop_constraint(None, 'merchants', type_='foreignkey')
    op.drop_column('merchants', 'city_id')
    op.drop_constraint(None, 'delivery_requests', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_requests_order_id_fkey'), 'delivery_requests', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preferred_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('bookings_customer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('bookings_listing_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('bookings_seller_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###
