"""add listing_id and dropoff fields

Revision ID: d1eab84964cd
Revises: b5d39e673914
Create Date: 2026-03-01 06:55:11.497952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1eab84964cd'
down_revision: Union[str, Sequence[str], None] = 'b5d39e673914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    # 1️⃣ Add columns as NULLABLE first
    op.add_column('orders', sa.Column('listing_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('dropoff_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_instructions', sa.String(), nullable=True))

    # 2️⃣ Create FK
    op.create_foreign_key(
        None,
        'orders',
        'listings',
        ['listing_id'],
        ['id'],
        ondelete='CASCADE'
    )

    # 3️⃣ TEMP FIX for existing rows
    # give old orders a safe placeholder listing
    op.execute("""
        UPDATE orders
        SET listing_id = (
            SELECT id FROM listings LIMIT 1
        )
        WHERE listing_id IS NULL
    """)

    # 4️⃣ Now enforce NOT NULL safely
    op.alter_column('orders', 'listing_id', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_instructions')
    op.drop_column('orders', 'dropoff_address')
    op.drop_column('orders', 'listing_id')
    op.alter_column('delivery_requests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_requests', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
