"""Delivery lifecycle integration

Revision ID: fc2c83eb4e3f
Revises: ba5174938481
Create Date: 2026-02-25 23:31:39.928101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2c83eb4e3f'
down_revision: Union[str, Sequence[str], None] = 'ba5174938481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_requests', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('delivery_requests', sa.Column('assigned_partner_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('delivery_requests_listing_id_fkey'), 'delivery_requests', type_='foreignkey')
    op.drop_constraint(op.f('delivery_requests_seller_id_fkey'), 'delivery_requests', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_requests', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'delivery_requests', 'delivery_partners', ['assigned_partner_id'], ['id'])
    op.create_foreign_key(None, 'delivery_requests', 'merchants', ['seller_id'], ['id'], ondelete='CASCADE')
    op.drop_column('delivery_requests', 'listing_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_requests', sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'delivery_requests', type_='foreignkey')
    op.drop_constraint(None, 'delivery_requests', type_='foreignkey')
    op.drop_constraint(None, 'delivery_requests', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_requests_seller_id_fkey'), 'delivery_requests', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('delivery_requests_listing_id_fkey'), 'delivery_requests', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.drop_column('delivery_requests', 'assigned_partner_id')
    op.drop_column('delivery_requests', 'order_id')
    # ### end Alembic commands ###
